// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZ76enwHKRZzwE9VW37Z49pSEmRwyXCU',
    appId: '1:688777038647:android:309f627a7445b0a89be8b2',
    messagingSenderId: '688777038647',
    projectId: 'karirvana-databases',
    storageBucket: 'karirvana-databases.firebasestorage.app',
  );
}
